# Generated by Django 5.0.6 on 2024-06-17 15:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.categorymodel'),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='U', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='date_listed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
