# Generated by Django 5.0.7 on 2024-07-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_userprofile_user_delete_marketplacecustomuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('related_seller', models.CharField(max_length=100)),
                ('related_sender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.item')),
            ],
        ),
    ]
