# Generated by Django 5.0.7 on 2024-07-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_usermessage_delete_sellercontactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.item'),
        ),
    ]
