# Generated by Django 5.0.7 on 2024-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_conversation_usermessage_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(related_name='conversation', to='marketplace.usermessage'),
        ),
    ]
