# Generated by Django 5.0.7 on 2024-07-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_usermessage_conversation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
