# Generated by Django 5.0.7 on 2024-08-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_message_chat_user_aichat_message_aichat_chatbot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aichat',
            old_name='content',
            new_name='user_message',
        ),
    ]
