# Generated by Django 5.0.7 on 2024-08-02 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_content_aichat_user_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='aichat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.aichat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
