# Generated by Django 5.0.7 on 2024-08-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_message_aichat_alter_message_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Bot')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='message',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
