# Generated by Django 5.0.7 on 2024-07-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_author',
        ),
    ]
