# Generated by Django 5.0.7 on 2024-08-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_likes_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloggerProfile',
        ),
    ]
